### PR TITLE
FIXED: to allow rgba() inside qlineargradient() stops

### PR DESCRIPTION
**Pull request by andvgal**
Current code fails with something like `qlineargradient(0, 0, 1,1, (0.1 rgba(0,0,0,0.5)))`.

A quick non-intrusive workaround is provided.

### CODE REVIEW

**Comment by goanpeca** [comment]
@andvgal thanks fornworking on this.

Could you provide a unit test for this issue?

**Comment by andvgal** [comment]
Just to be clear, I had checked that there was no `rgba()` or `qlineargradient()` parser tests. The test were only available for conformers, but for this case those are useless.

During testing,it appeared that `qlineargradient()` did not put commas between stops, fixed as well.

Conversion of QSS to SCSS with nested `rgba()` is out of scope of this PR, but placeholder test with TODO log is added.

**Comment by goanpeca** [comment]
@andvgal could you rebase or merge with master and update this PR?

**Comment by danbradham** [comment]
Thanks for fixing those stops @andvgal.

If you rebase you'll notice there was a change to `api.compile`, it now acts on strings directly and passes all kwargs to `sass.compile`. That should eliminate the necessity of the `api.compile_source` function that you added. You can use the `include_paths` argument to pass a list of directories if you need to. 

`api.compile(string, include_paths=[...])`

The rest of your changes should fall into place.

**Comment by andvgal** [comment]
Done

**Comment by goanpeca** [comment]
Good to merge @danbradham :-) ?

**Comment by danbradham** [comment]
yessir @goanpeca

**Comment by goanpeca** [comment]
@andvgal could we merge/rebase with master so we can get the test on Travis going?

Thanks!

**Comment by andvgal** [comment]
Rebased and allowed mods to edit.

**Comment by goanpeca** [comment]
Thanks for working on this!!

**Pull request merged**
