### PR TITLE
PR: Reorganize package

### LINKED ISSUE #21: Reorganize qtsass package
QtSass centers around the sass.compile command, I think the organization of the package should reflect this. Going forward this would also provide obvious locations for additional components.
```
qtsass/
  __init__.py
  __main__.py
  api.py
  conformers.py
  events.py
  functions.py
  importers.py
```

### PR DESCRIPTION
**Pull request by danbradham**
resolves #21

What do you think about this @goanpeca?

### CODE REVIEW

**Comment by goanpeca** [comment]
Sure sounds good. but why the __main__ file? seems like an odd name

**Comment by danbradham** [comment]
If you do python -m qtsass, python sees the __main__ file and executes it. Similar to a __name__ =="__main__" block in a module. Makes it easy to invoke the cli while developing.

**Comment by goanpeca** [comment]
>Makes it easy to invoke the cli while developing.

That should not be a reason to do it. You could do a `python setup.py develop` instead to work on dev mode. I would change that to `cli.py` its more clear.

**Comment by danbradham** [comment]
Including a `__main__.py` is fairly standard practice, it's the reason you can do python -m pip and python -m unittest. Looking forward, if someone wanted to vendor qtsass in one of their own projects and continue to use the cli tool, including a `__main__.py` makes that possibility much easier. Also, I'd counter your point that easing development isn't a valid point, by saying, yes it is =). I prefer not to pollute my workspace with develop installs.

https://github.com/python/cpython/tree/master/Lib/unittest

I agree with you that the main functions shouldn't be in `__main__.py`. How about I move the main and main_parser functions into cli.py and have the `__main__.py` file import and call cli.main?

**Comment by goanpeca** [comment]
>I agree with you that the main functions shouldn't be in __main__.py. How about I move the main and main_parser functions into cli.py and have the __main__.py file import and call cli.main?

Ok, that sounds better

**Pull request merged**
