### PR TITLE
Add Watcher api

### PR DESCRIPTION
**Pull request by danbradham**
Addresses #41 

This PR introduces a new Watcher api that abstracts the watch functionality that was originally provided by watchdog. Now, if watchdog is available the watch api method will return a WatchdogWatcher object. If not a fallback implementation called PollingWatcher is returned instead. The PollingWatcher is implemented in pure python so not only do we remove the dependency on watchdog, but we ensure that the watch functionality will always be available. Finally a QtWatcher has been stubbed out in this initial PR, but, it doesn't work yet.

The default Watcher is the first available in this list:
- QtWatcher
- WatchdogWatcher
- PollingWatcher

The Watcher api also allows you to attach additional callbacks to be run after a change is detected. This will make it easy to live-reload stylesheets for a QWidget or QApplication.
```
import qtsass
watcher = qtsass.watch('path/to/src.scss', 'path/to/dest.css')

def live_reload(widget):
    def do_reload(css):
        widget.setStyleSheet(css)
    return do_reload

watcher.connect(live_reload(some_widget))
```

TODO

- [x] Finish QtWatcher implementation
- [x] Add tests for each Watcher implementation
- [x] Document all methods to satisfy formatting checks

### CODE REVIEW

**Comment by goanpeca** [comment]
@danbradham 

The fix for this was to add an `extras_require` on setup.py. Or add the try except on imports since this is not really a crucial functionality.

Now we should probably depend on `qtpy` for avoiding the need to check all what Qt package is being used.

**Comment by danbradham** [comment]
@goanpeca do you think I should still add extras_require even with the fallback that works without watchdog?

This branch removes the requirement by falling back to a PollingWatcher that's implemented in pure python. I created the WatchdogWatcher as a reference implementation of the Watcher api to make sure I didn't break anything while refactoring. I'm still open to extra_requires I just felt like it wasn't necessary anymore.

This PR addresses #41 as a side-effect of refactoring the watch functionality. I understand that this probably looks like overkill for tl rhe initiaequest to remove the requirement on watchdog. I agree, it kind of is! But, I have an interest in supporting richer live reloading in my Qt dev environments. Perhaps I should have created an additional ticket with that in mind.

In regards to qtpy, I work in the VFX domain and we all use Qt.py for compatibility, which is a very similar library. There are few enough dependencies in the QtWatcher that it doesn't seem like that big a deal to cascade through Qt bindings manually rather than relying on a specific qt compatability library.

Does that make sense? My opinions aren't too strong on these details, I'm just working through them as they come up.

**Comment by goanpeca** [comment]
>@goanpeca do you think I should still add extras_require even with the fallback that works without watchdog?

Well yes since there should be some way to discover this... extras is that way... normal qtsass install does not include it, but with an extra it does.

>This branch removes the requirement by falling back to a PollingWatcher that's implemented in pure python. I created the WatchdogWatcher as a reference implementation of the Watcher api to make sure I didn't break anything while refactoring. I'm still open to extra_requires I just felt like it wasn't necessary anymore.

Sure, we could just use the polling one, but then what is the idea of keeping a watchdog one? I am confused.

>This PR addresses #41 as a side-effect of refactoring the watch functionality. I understand that this probably looks like overkill for tl rhe initiaequest to remove the requirement on watchdog. I agree, it kind of is! But, I have an interest in supporting richer live reloading in my Qt dev environments. Perhaps I should have created an additional ticket with that in mind.

Perhaps

>In regards to qtpy, I work in the VFX domain and we all use Qt.py for compatibility, which is a very similar library. There are few enough dependencies in the QtWatcher that it doesn't seem like that big a deal to cascade through Qt bindings manually rather than relying on a specific qt compatability library.

Ok, we could make this exception I guess, but please write a descriptive comment on why this was decided

Thanks!

**Comment by danbradham** [comment]
Almost there with this I think. Looks like I've got a couple issues to fix and the code formatting errors came over from @ewerybody 's PR when I rebased. I'll see if I can take care of those in the next couple of days.

@goanpeca you were right about watchdog not being necessary, removed it in this set of commits.

The QtWatcher is now implemented as a subclass of PollingWatcher, that dispatches using a Qt Signal once a QApplication has been started. I've added PySide2 to requirements-dev.txt for Python 3.6 so that this gets tested properly.

**Comment by goanpeca** [comment]
>Almost there with this I think. Looks like I've got a couple issues to fix and the code formatting errors came over from @ewerybody 's PR when I rebased. I'll see if I can take care of those in the next couple of days.

Thanks!

>The QtWatcher is now implemented as a subclass of PollingWatcher, that dispatches using a Qt Signal once a QApplication has been started. I've added PySide2 to requirements-dev.txt for Python 3.6 so that this gets tested properly.

Great :-)

Thanks for working on this, let me know when this is ready for a final review :-)

**Comment by danbradham** [comment]
@goanpeca this ready for review when you get the chance. 

I will have to do one last commit to fix the isort failures but the actual tests are passing now.

**Comment by ewerybody** [comment]
> Almost there with this I think. Looks like I've got a couple issues to fix and the code formatting errors came over from @ewerybody 's PR when I rebased. I'll see if I can take care of those in the next couple of days.

Hey, I really wish I would have known what was wrong!! The checks ran through on my machine. They just popped on the CI `¯\_(ツ)_/¯`

**Pull request merged**
