### PR TITLE
PR: Add the support for QRadialGradient

### LINKED ISSUE #57: Unsupported qradialgradient
qradialgradient is not supported. Example of typical usage:

```
QRadioButton::indicator:checked
{
	background-color: qradialgradient(
		cx: 0.5, cy: 0.5,
		fx: 0.5, fy: 0.5,
		radius: 1.0,
		stop: 0.25 #78879b,
		stop: 0.3 #302F2F
	);
}
```

### PR DESCRIPTION
**Pull request by regrainb**
Fixes #57

### CODE REVIEW

**Comment by dalthviz** [comment]
Hi @regrainb sorry for such a delayed response. I think that what is missing here for this to be merged is to rebase on top of the latest changes done to the repo and add a test for the changes you added here.

Let us know if you want to continue with the work here or if is okay for someone else to finish the missing things!

**Comment by regrainb** [comment]
Hi Daniel,
I'm switched to other things.I have no issues to let someone else finishing the work. It will be really useful to have these adds on you tool

Best regardsBenoit


    Le vendredi 16 septembre 2022 à 19:16:17 UTC+2, Daniel Althviz Moré ***@***.***> a écrit :  
 
 


Hi @regrainb sorry for such a delayed response. I think that what is missing here for this to be merged is to rebase on top of the latest changes done to the repo and add a test for the changes you added here.

Let us know if you want to continue with the work here or if is okay for someone else to finish the missing things!

**Comment by regrainb** [comment]
@ccordoba12 : When do you plan doing a new tag?
We would use your last tag, but doesn't that change.

**Comment by ccordoba12** [comment]
@dalthviz is the maintainer of this repo. @dalthviz, when do you have time to make a new QtSass release?

**Pull request merged**
